server:
  port: 8080
spring:
  datasource:
    name: iot_classroom
    url: jdbc:mysql://localhost:3306/iot_classroom?characterEncoding=utf8&useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
